server:
  port: 8080

spring:
  datasource:
# My current IP, should be publicly available mysql server (for tests purpose only)
    url: jdbc:mysql://10.93.90.193:3306/reservations_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
